<?php
    require_once("functions.php");
    $array_categoria=array(
        1=>[
            "id_categoria"=>1,
            "nombre"=>"Oro"
        ],
        2=>[
            "id_categoria"=>2,
            "nombre"=>"Plata"
        ],
        3=>[
            "id_categoria"=>3,
            "nombre"=>"Platino"
        ],
        4=>[
            "id_categoria"=>4,
            "nombre"=>"Deportivo"
        ],
        5=>[
            "id_categoria"=>5,
            "nombre"=>"Cromado"
        ]
    );
    GrabarArrayJson("Json","categorias.json",$array_categoria);
?>